#!/bin/bash
shopt -s extglob
shopt -s globstar

REPO_SLUG="${SILENTGUARD_GITHUB_REPO:-OptimusFaber/SilentGuard}"
OBS_TRIGGER_PROJECT="${OBS_TRIGGER_PROJECT:-home:YOUR_OBS_USER}"
OBS_TRIGGER_PACKAGE="${OBS_TRIGGER_PACKAGE:-silentguard}"
OBS_SOURCE_PROJECT="${OBS_SOURCE_PROJECT:-network:YOUR_PROJECT}"
OBS_SOURCE_PACKAGE="${OBS_SOURCE_PACKAGE:-silentguard}"
PKG="$OBS_SOURCE_PACKAGE"

curl -u "${OBS_USER}:${OBS_PASSWORD}"   -X POST   "https://api.opensuse.org/source/${OBS_TRIGGER_PROJECT}/${OBS_TRIGGER_PACKAGE}?cmd=runservice"
curl -u "${OBS_USER}:${OBS_PASSWORD}" \
  "https://api.opensuse.org/source/${OBS_SOURCE_PROJECT}/${OBS_SOURCE_PACKAGE}/${PKG}.changes" \
  -o "${PKG}.changes"

export pkgver="$INPUT_VERSION"
export source_0="https://github.com/${REPO_SLUG}/releases/download/${pkgver}/silentguard-unified-source-${pkgver}.tar.xz"

curl -L "https://raw.githubusercontent.com/${REPO_SLUG}/refs/heads/main/${PKG}.spec" -o "${PKG}.spec"
curl -L "https://raw.githubusercontent.com/${REPO_SLUG}/refs/heads/main/${PKG}-core.spec.in" -o "${PKG}-core.spec.in"
curl -L "https://raw.githubusercontent.com/${REPO_SLUG}/refs/heads/main/${PKG}-qt.spec.in" -o "${PKG}-qt.spec.in"

sed -i "s@Version:.*@Version:        $pkgver@g;" "${PKG}.spec"

file_0="$(basename "${source_0}")"

curl -L "${source_0}" -o "${file_0}"

python -c "
import os
text = ''
if os.path.exists('${PKG}.changes'):
 f=open('${PKG}.changes', 'r')
 text=f.read()
 f.close()
msg='''${MESSAGE}'''
import textwrap
def wrap_preserve_newlines(text, width):
 return '\n'.join([textwrap.fill(line, width) if line.strip() else '' for line in text.splitlines()])
if len(msg) > 0 and 'Update to ${pkgver}' not in text:
 msg = wrap_preserve_newlines(msg, 65)
 if msg[-1] != '\n':
  msg = msg + '\n'
 k='-------------------------------------------------------------------'
 k+='\n$(date) - ${USER} <${EMAIL}>\n\n'
 k+='Update to ${pkgver}\n' + msg + '\n'
 text=k+text
 f=open('${PKG}.changes', 'w')
 f.write(text)
 f.close()
print(text)
"

curl -s -u "${OBS_USER}:${OBS_PASSWORD}"   "https://api.opensuse.org/source/${OBS_SOURCE_PROJECT}/${OBS_SOURCE_PACKAGE}" | grep -oP '<entry[^>]*\sname="\K[^"]+' | while IFS= read -r name
do
curl -u "${OBS_USER}:${OBS_PASSWORD}" -X DELETE "https://api.opensuse.org/source/${OBS_SOURCE_PROJECT}/${OBS_SOURCE_PACKAGE}/${name}"
done

for i in "${PKG}.changes" "${PKG}.spec" "${PKG}-core.spec.in" "${PKG}-qt.spec.in" "${file_0}"
do
curl -u "${OBS_USER}:${OBS_PASSWORD}" \
  -X PUT \
  -H "Content-Type: text/plain" \
  --data-binary @"${i}" \
  "https://api.opensuse.org/source/${OBS_SOURCE_PROJECT}/${OBS_SOURCE_PACKAGE}/${i}"
done

if [[ "$SUBMIT_FACTORY" == 'true' ]]
then
newline="$(echo -e '\n ')"
curl -u "${OBS_USER}:${OBS_PASSWORD}"   -X POST   -H "Content-Type: application/xml"   -d '
<request>
  <action type="submit">
    <source project="'"${OBS_SOURCE_PROJECT}"'" package="'"${OBS_SOURCE_PACKAGE}"'"/>
    <target project="openSUSE:Factory" package="'"${OBS_SOURCE_PACKAGE}"'"/>
  </action>
  <description>'"Update to $pkgver. ${newline}${MESSAGE}${newline}${newline} Generated by Github Actions."'</description>
</request>'   'https://api.opensuse.org/request?cmd=create'
fi

