#!/bin/bash -x

declare -A specs=(["silentguard"]="PKGBUILD" ["silentguard-git"]="aur_git/PKGBUILD")

for i in 'silentguard' 'silentguard-git'
do
echo "${specs[$i]}"
git clone ssh://aur@aur.archlinux.org/"${i}".git "aur-$i"
cp "${specs[$i]}" "aur-$i/PKGBUILD"
pushd "aur-$i"

if command -v "makepkg"
then
makepkg --printsrcinfo > .SRCINFO
git add --all
git commit -am "$MESSAGE. Generated by Github Action"
git push --force
fi

popd
done
